name: Checking Ref Name
on: push

jobs:
  checking-ref-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Ref Name
        run: |
          echo ref: "${{ github.ref }}"
          echo ref_name: "${{ github.ref_name }}"
