name: 01 - Steps Outputs Demo

on:
  workflow_dispatch:

jobs:
  steps-job-output:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Release Version
        id: version
        run: |
          echo "release_version=v1.0.0" >> $GITHUB_OUTPUT

      - name: Deploy Applications...
        id: deploy
        run: |
          echo "Display Application ..."
          echo "deployment_url=BadhonBiswas.dev" >> $GITHUB_OUTPUT

      - name: Display Release Version
        run: |
          echo "${{steps.version.outputs.release_version}}"

      - name: Display Deployment Details
        run: |
          echo "Application deployed successfully"
          echo "Deployment URL"
          echo "${{steps.deploy.outputs.deployment_url}}"
