name: Checking Ref Name
on: push

jobs:
  checking-ref-name:
    runs-on: ubuntu-latest

    steps:
      - name: Badhon112
        if: ${{ github.ref == 'refs/heads/Badhon112' }}
        run: |
          echo "Hello From refs/heads/Badhon112"

      - name: main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "Hello From main"