name: Hello World
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: |
          echo "A Demo Build For Test"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test Step
        run: |
          echo "Running a Build Test"
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy Step
        run: |
          echo "Running a Deploy Stage"
